data = {
   "MIT License":{
      "Repositories":{
         "type":"Repositories",
         "count":"1125",
         "codeDist":{
            "JavaScript":"146",
            "Python":"89",
            "PHP":"64",
            "C#":"63",
            "C++":"63",
            "Java":"57",
            "HTML":"50",
            "C":"43",
            "CSS":"35",
            "Shell":"23"
         }
      },
      "Code":{
         "type":"Code",
         "count":"86466129",
         "codeDist":{
            "JavaScript":"19,520,562",
            "PHP":"16,625,280",
            "SVG":"8,200,235",
            "CSS":"7,441,266",
            "JSON":"7,081,783",
            "HTML":"4,412,489",
            "C++":"4,153,223",
            "Text":"3,121,640",
            "Markdown":"2,642,741",
            "Python":"1,862,553"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"836015",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"274136",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"922",
         "codeDist":{
            "Npm":"908",
            "Docker":"5",
            "Nuget":"5",
            "Rubygems":"4"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"2",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"13267",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"35",
         "codeDist":{
            "JavaScript":"10",
            "Python":"6",
            "HTML":"3",
            "CSS":"2",
            "PHP":"2",
            "AutoIt":"1",
            "C#":"1",
            "C++":"1",
            "Java":"1",
            "Objective-C":"1"
         }
      }
   },
   "Apache License":{
      "Repositories":{
         "type":"Repositories",
         "count":"498",
         "codeDist":{
            "Java":"107",
            "JavaScript":"27",
            "HTML":"26",
            "Python":"19",
            "C++":"16",
            "C":"12",
            "PHP":"12",
            "CSS":"9",
            "Objective-C":"9",
            "C#":"8"
         }
      },
      "Code":{
         "type":"Code",
         "count":"132471219",
         "codeDist":{
            "Java":"38,444,885",
            "XML":"16,767,589",
            "PHP":"13,628,634",
            "JavaScript":"9,829,016",
            "C++":"9,207,564",
            "Python":"6,722,016",
            "HTML":"4,377,985",
            "C":"4,185,958",
            "Objective-C":"3,132,483",
            "Markdown":"2,819,723"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"325452",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"180081",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"125",
         "codeDist":{
            "Npm":"120",
            "Docker":"2",
            "Maven":"2",
            "Nuget":"1"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"2",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"12699",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"15",
         "codeDist":{
            "Go":"2",
            "Java":"2",
            "PHP":"2",
            "ActionScript":"1",
            "C++":"1",
            "JavaScript":"1",
            "Makefile":"1",
            "Python":"1",
            "Ruby":"1",
            "Shell":"1"
         }
      }
   },
   "GPLv3":{
      "Repositories":{
         "type":"Repositories",
         "count":"833",
         "codeDist":{
            "C++":"110",
            "Python":"110",
            "Java":"101",
            "C":"70",
            "PHP":"49",
            "JavaScript":"45",
            "C#":"36",
            "Shell":"30",
            "HTML":"19",
            "Kotlin":"16"
         }
      },
      "Code":{
         "type":"Code",
         "count":"5992034",
         "codeDist":{
            "Objective-C":"2,258,414",
            "PHP":"883,255",
            "JavaScript":"320,564",
            "Text":"251,237",
            "XML":"196,323",
            "C":"180,755",
            "Shell":"180,643",
            "Makefile":"152,168",
            "Python":"137,486",
            "JSON":"133,496"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"180670",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"33152",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"4",
         "codeDist":{
            "Npm":"4"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"2",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"2489",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"8",
         "codeDist":{
            "Lua":"2",
            "C++":"1",
            "HTML":"1",
            "Python":"1"
         }
      }
   },
   "BSD 2-clause":{
      "Repositories":{
         "type":"Repositories",
         "count":"37",
         "codeDist":{
            "C":"4",
            "C++":"3",
            "Java":"3",
            "JavaScript":"3",
            "Python":"3",
            "Perl":"2",
            "C#":"1",
            "Go":"1",
            "HTML":"1",
            "Hack":"1"
         }
      },
      "Code":{
         "type":"Code",
         "count":"1606857",
         "codeDist":{
            "JavaScript":"627,549",
            "C":"392,915",
            "Text":"98,374",
            "Python":"77,703",
            "C++":"62,212",
            "HTML":"40,652",
            "JSON":"32,050",
            "Markdown":"31,682",
            "CMake":"23,836",
            "XML":"23,550"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"146007",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"16212",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"10",
         "codeDist":{
            "Npm":"9",
            "Nuget":"1"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"2",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"1129",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"2",
         "codeDist":{

         }
      }
   },
   "BSD 3-clause":{
      "Repositories":{
         "type":"Repositories",
         "count":"43",
         "codeDist":{
            "C":"10",
            "Python":"5",
            "C++":"4",
            "TeX":"2",
            "HTML":"1",
            "Handlebars":"1",
            "Java":"1",
            "Jupyter Notebook":"1",
            "PHP":"1",
            "Pascal":"1"
         }
      },
      "Code":{
         "type":"Code",
         "count":"7098749",
         "codeDist":{
            "PHP":"1,795,484",
            "Python":"1,488,896",
            "C":"1,185,044",
            "C++":"426,086",
            "XML":"362,743",
            "Text":"284,327",
            "Markdown":"232,080",
            "CMake":"156,498",
            "JSON":"142,732",
            "HTML":"118,749"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"722897",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"24361",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"14",
         "codeDist":{
            "Npm":"13",
            "Nuget":"1"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"3",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"1240",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"3",
         "codeDist":{

         }
      }
   },
   "GPLv2":{
      "Repositories":{
         "type":"Repositories",
         "count":"213",
         "codeDist":{
            "C":"50",
            "PHP":"29",
            "C++":"26",
            "Python":"15",
            "Java":"11",
            "JavaScript":"10",
            "C#":"5",
            "CSS":"5",
            "Go":"5",
            "Perl":"5"
         }
      },
      "Code":{
         "type":"Code",
         "count":"32138069",
         "codeDist":{
            "C":"19,518,149",
            "C++":"1,718,607",
            "Java":"1,516,615",
            "Makefile":"905,277",
            "PHP":"819,974",
            "Text":"635,256",
            "Unix Assembly":"511,171",
            "JavaScript":"467,773",
            "XML":"387,267",
            "BitBake":"279,154"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"1621163",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"14794",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"2",
         "codeDist":{
            "Npm":"2"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"1",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"1640",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"2",
         "codeDist":{
            "PHP":"2"
         }
      }
   },
   "GPLv2.1":{
      "Repositories":{
         "type":"Repositories",
         "count":"10",
         "codeDist":{
            "C":"2",
            "Assembly":"1",
            "CSS":"1",
            "Java":"1",
            "Lua":"1",
            "M":"1",
            "PHP":"1",
            "Perl":"1"
         }
      },
      "Code":{
         "type":"Code",
         "count":"30865749",
         "codeDist":{
            "C":"18,788,757",
            "C++":"1,651,636",
            "Java":"1,510,999",
            "Makefile":"858,226",
            "PHP":"783,416",
            "Text":"608,011",
            "Unix Assembly":"490,580",
            "JavaScript":"448,977",
            "XML":"372,516",
            "BitBake":"267,817"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"302056",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"21",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"2",
         "codeDist":{

         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"2",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"4",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"2",
         "codeDist":{

         }
      }
   },
   "LGPLv2.1":{
      "Repositories":{
         "type":"Repositories",
         "count":"8",
         "codeDist":{
            "C":"3",
            "Java":"3",
            "C#":"1",
            "Shell":"1"
         }
      },
      "Code":{
         "type":"Code",
         "count":"1024847",
         "codeDist":{
            "XML":"154,495",
            "Makefile":"146,488",
            "C":"142,250",
            "PHP":"115,446",
            "BitBake":"106,796",
            "JSON":"89,515",
            "C++":"21,145",
            "JavaScript":"20,881",
            "Text":"18,333",
            "RPM Spec":"15,006"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"38069",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"672",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"2",
         "codeDist":{

         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"2",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"139",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"1",
         "codeDist":{
            "HTML":"1"
         }
      }
   },
   "LGPLv3":{
      "Repositories":{
         "type":"Repositories",
         "count":"68",
         "codeDist":{
            "Java":"13",
            "C++":"11",
            "C":"8",
            "C#":"7",
            "PHP":"6",
            "JavaScript":"3",
            "Python":"3",
            "Shell":"3",
            "Go":"2",
            "ApacheConf":"1"
         }
      },
      "Code":{
         "type":"Code",
         "count":"2682248",
         "codeDist":{
            "C++":"1,017,907",
            "QML":"529,158",
            "PHP":"338,534",
            "C":"150,667",
            "XML":"147,240",
            "JavaScript":"80,802",
            "Python":"65,772",
            "Text":"43,272",
            "Makefile":"41,883",
            "JSON":"34,622"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"22268",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"2063",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"3",
         "codeDist":{

         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"2",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"295",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"1",
         "codeDist":{
            "Clojure":"1"
         }
      }
   },
   "Mozilla Public License":{
      "Repositories":{
         "type":"Repositories",
         "count":"31",
         "codeDist":{
            "Java":"7",
            "JavaScript":"3",
            "C++":"2",
            "HTML":"2",
            "ActionScript":"1",
            "C":"1",
            "C#":"1",
            "Handlebars":"1",
            "Pascal":"1"
         }
      },
      "Code":{
         "type":"Code",
         "count":"29244773",
         "codeDist":{
            "C++":"9,102,859",
            "JavaScript":"5,737,901",
            "Python":"4,685,537",
            "C":"1,968,953",
            "Java":"1,013,136",
            "HTML":"962,357",
            "PHP":"596,935",
            "Markdown":"426,059",
            "XML":"414,819",
            "INI":"400,485"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"4877",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"5399",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"13",
         "codeDist":{
            "Npm":"13"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"1",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"1202",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"000000",
         "codeDist":{

         }
      }
   },
   "The Unilicense":{
      "Repositories":{
         "type":"Repositories",
         "count":0,
         "codeDist":{

         }
      },
      "Code":{
         "type":"Code",
         "count":"110",
         "codeDist":{
            "Markdown":"47",
            "Text":"13",
            "Python":"10",
            "Go":"8",
            "JSON":"6",
            "C":"4",
            "C++":"3",
            "HTML":"3",
            "YAML":"3",
            "AsciiDoc":"2"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"10",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"14",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":0,
         "codeDist":{

         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":0,
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"1",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":0,
         "codeDist":{

         }
      }
   },
   "Boost Software License":{
      "Repositories":{
         "type":"Repositories",
         "count":"6",
         "codeDist":{
            "C++":"3",
            "Perl":"3"
         }
      },
      "Code":{
         "type":"Code",
         "count":"64011467",
         "codeDist":{
            "C++":"46,582,703",
            "HTML":"7,092,412",
            "C":"5,688,298",
            "XML":"312,385",
            "Python":"280,001",
            "reStructuredText":"217,388",
            "Text":"206,518",
            "Gettext Catalog":"198,510",
            "Java":"190,737",
            "Markdown":"170,289"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"3516",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"3105",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"3",
         "codeDist":{
            "Npm":"3"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":0,
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"1658",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":0,
         "codeDist":{

         }
      }
   },
   "Pre-Release Software":{
      "Repositories":{
         "type":"Repositories",
         "count":"25",
         "codeDist":{
            "C++":"4",
            "C":"1",
            "C#":"1",
            "Fortran":"1",
            "Java":"1",
            "JavaScript":"1",
            "Python":"1",
            "VBScript":"1"
         }
      },
      "Code":{
         "type":"Code",
         "count":"1552047",
         "codeDist":{
            "Python":"649,391",
            "XML":"357,717",
            "C++":"149,840",
            "C":"75,831",
            "HTML":"47,033",
            "Text":"24,480",
            "PHP":"23,957",
            "JavaScript":"19,920",
            "Gettext Catalog":"18,507",
            "Markdown":"18,476"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"78200",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"32570",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"7",
         "codeDist":{
            "Npm":"7"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":0,
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"7377",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":0,
         "codeDist":{

         }
      }
   },
   "CC0-1.0":{
      "Repositories":{
         "type":"Repositories",
         "count":"36",
         "codeDist":{
            "HTML":"4",
            "JavaScript":"3",
            "C":"2",
            "C#":"1",
            "CSS":"1",
            "Java":"1",
            "Lua":"1",
            "Python":"1",
            "R":"1"
         }
      },
      "Code":{
         "type":"Code",
         "count":"131448",
         "codeDist":{
            "JSON":"31,607",
            "JavaScript":"15,921",
            "XML":"15,892",
            "HTML":"10,137",
            "Ruby":"8,119",
            "Markdown":"8,050",
            "Python":"4,336",
            "Verilog":"3,638",
            "Gentoo Ebuild":"3,554",
            "Makefile":"2,217"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"11011",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"2340",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"0",
         "codeDist":{

         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"0",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"348",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"0",
         "codeDist":{

         }
      }
   },
   "CC-BY-4":{
      "Repositories":{
         "type":"Repositories",
         "count":"297",
         "codeDist":{
            "HTML":"26",
            "TeX":"12",
            "JavaScript":"11",
            "Python":"11",
            "C++":"9",
            "CSS":"7",
            "R":"4",
            "C#":"3",
            "Lua":"3",
            "PHP":"3"
         }
      },
      "Code":{
         "type":"Code",
         "count":"194154",
         "codeDist":{
            "JSON":"81,703",
            "HTML":"19,823",
            "YAML":"15,758",
            "Markdown":"14,781",
            "XML":"12,571",
            "Python":"10,225",
            "Text":"3,314",
            "Prolog":"2,881",
            "reStructuredText":"1,838",
            "JavaScript":"1,197"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"21290484",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"406748",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"7",
         "codeDist":{
            "Npm":"6",
            "Docker":"1"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"4",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"13351",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"4",
         "codeDist":{

         }
      }
   },
   "CC-BY-SA-4":{
      "Repositories":{
         "type":"Repositories",
         "count":"147",
         "codeDist":{
            "HTML":"12",
            "Python":"6",
            "TeX":"6",
            "C++":"5",
            "JavaScript":"4",
            "CSS":"3",
            "Lua":"3",
            "C#":"2",
            "PHP":"2",
            "Assembly":"1"
         }
      },
      "Code":{
         "type":"Code",
         "count":"43448",
         "codeDist":{
            "JSON":"6,491",
            "Markdown":"5,111",
            "YAML":"4,744",
            "HTML":"2,625",
            "XML":"2,178",
            "Gentoo Ebuild":"1,752",
            "Makefile":"1,743",
            "reStructuredText":"1,482",
            "AsciiDoc":"788",
            "PHP":"771"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"175508",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"10202",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"2",
         "codeDist":{
            "Npm":"2"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"000000",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"4",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"2098",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"4",
         "codeDist":{

         }
      }
   },
   "copyright":{
      "Repositories":{
         "type":"Repositories",
         "count":"3924",
         "codeDist":{
            "JavaScript":"384",
            "HTML":"337",
            "Python":"305",
            "Java":"285",
            "PHP":"273",
            "Ruby":"154",
            "C++":"132",
            "C#":"121",
            "CSS":"105",
            "C":"96"
         }
      },
      "Code":{
         "type":"Code",
         "count":"337798568",
         "codeDist":{
            "C":"126,197,595",
            "PHP":"51,676,134",
            "C++":"32,835,872",
            "Java":"19,144,904",
            "JavaScript":"17,360,022",
            "HTML":"16,271,165",
            "Python":"8,703,677",
            "XML":"7,965,094",
            "Text":"5,500,828",
            "Objective-C":"4,977,126"
         }
      },
      "Commits":{
         "type":"Commits",
         "count":"15509780",
         "codeDist":{

         }
      },
      "Issues":{
         "type":"Issues",
         "count":"592910",
         "codeDist":{

         }
      },
      "RegistryPackages":{
         "type":"RegistryPackages",
         "count":"250",
         "codeDist":{
            "Npm":"245",
            "Maven":"5"
         }
      },
      "Marketplace":{
         "type":"Marketplace",
         "count":"3",
         "codeDist":{

         }
      },
      "Topics":{
         "type":"Topics",
         "count":"22",
         "codeDist":{

         }
      },
      "Wikis":{
         "type":"Wikis",
         "count":"44707",
         "codeDist":{

         }
      },
      "Users":{
         "type":"Users",
         "count":"313",
         "codeDist":{
            "JavaScript":"23",
            "Python":"23",
            "HTML":"22",
            "Java":"19",
            "C++":"11",
            "PHP":"11",
            "CSS":"10",
            "C#":"8",
            "C":"6",
            "Ruby":"6"
         }
      }
   }
}
